default:
  cacheEnabled: false
  maxElementsInMemory: 100
  overflowToDisc: false
  overflowToDisk: false
  diskPersistent: false
  diskExpiryThreadIntervalSeconds: 0
  eternal: true
  timeToLiveSeconds: 0
  timeToIdleSeconds: 0
  statisticsEnabled: false

configCache:
  cacheEnabled: false
  eternal: true
  statisticsEnabled: false

objectDataCache:
  cacheEnabled: false
  statisticsEnabled: false

propertisCache:
  cacheEnabled: false
  maxElementsInMemory: 10
  statisticsEnabled: false

typeCache:
  cacheEnabled: false
  maxElementsInMemory: 1
  statisticsEnabled: false

contentCache:
  cacheEnabled: false
  statisticsEnabled: false

treeCache:
  cacheEnabled: false
  statisticsEnabled: false

versionSeriesCache:
  cacheEnabled: false
  statisticsEnabled: false

attachmentCache:
  cacheEnabled: false
  statisticsEnabled: false

changeEventCache:
  cacheEnabled: false
  statisticsEnabled: false

latestChangeTokenCache:
  cacheEnabled: false
  maxElementsInMemory: 1
  statisticsEnabled: false

userCache:
  cacheEnabled: false
  statisticsEnabled: false

usersCache:
  cacheEnabled: false
  statisticsEnabled: false

groupCache:
  cacheEnabled: false
  statisticsEnabled: false

groupsCache:
  cacheEnabled: false
  statisticsEnabled: false

aclCache:
  cacheEnabled: false
  statisticsEnabled: false

joinedGroupCache:
  cacheEnabled: false
  statisticsEnabled: false