repositories:
  - id: canopy
    name: canopy
    archive: canopy_closet
    root: canopy00000000000000000000000000000
  - id: bedroom
    name: bedroom
    archive: bedroom_closet
    root: e02f784f8360a02cc14d1314c10038ff
