!jp.aegif.nemaki.util.yaml.RepositorySettings
settings: 
   canopy: !jp.aegif.nemaki.util.yaml.RepositorySetting
      password: admin
      user: admin
   bedroom: !jp.aegif.nemaki.util.yaml.RepositorySetting
      password: admin
      user: admin
